server:
  port: 80

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.demo.springcloud.entity


spring:
  application:
    name: cloud-order-service
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka6001.com:6001/eureka,http://eureka6002.com:6002/eureka
  instance:
    instance-id: consumer80 #主机名修改
    prefer-ip-address: true #访问路径可以显示ip